spring.application.name=ATBP3Laba
spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=postgres
spring.datasource.password=OOPIP228337
spring.jpa.hibernate.ddl-auto=update

server.port=8082